version: '3.7'

networks:
  backend_shared:
    name: backend_shared

services:
  redis:
    image: "redis:latest"
    networks:
     - backend_shared
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    environment:
      - RABBITMQ_DEFAULT_USER=fleet
      - RABBITMQ_DEFAULT_PASS=fleet
    networks:
      - backend_shared
