"""baseline

Revision ID: 99445ea7335e
Revises: 
Create Date: 2026-08-05 07:49:20.819779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99445ea7335e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowed_starts',
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('addition_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_allowed_starts'))
    )
    op.create_table('fuel_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('refers_to', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fuel_types'))
    )
    op.create_table('leasing_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leasing_types'))
    )
    op.create_table('simulation_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_simulation_settings'))
    )
    op.create_table('user_login',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('last_seen_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_login'))
    )
    op.create_table('vehicle_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('refers_to', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicle_types'))
    )
    op.create_table('workshops',
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('addition_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workshops'))
    )
    op.create_table('allowed_start_additions',
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('allowed_start_id', sa.Integer(), nullable=False),
    sa.Column('addition_date', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['allowed_start_id'], ['allowed_starts.id'], name=op.f('fk_allowed_start_additions_allowed_start_id_allowed_starts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_allowed_start_additions'))
    )
    with op.batch_alter_table('allowed_start_additions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allowed_start_additions_allowed_start_id'), ['allowed_start_id'], unique=False)

    op.create_table('cars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('imei', sa.String(length=20), nullable=True),
    sa.Column('plate', sa.String(length=128), nullable=True),
    sa.Column('make', sa.String(length=128), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('fuel', sa.Integer(), nullable=True),
    sa.Column('wltp_fossil', sa.Float(), nullable=True),
    sa.Column('wltp_el', sa.Float(), nullable=True),
    sa.Column('capacity_decrease', sa.Float(), nullable=True),
    sa.Column('co2_pr_km', sa.Float(), nullable=True),
    sa.Column('range', sa.Float(), nullable=True),
    sa.Column('omkostning_aar', sa.Float(), nullable=True),
    sa.Column('location', sa.Integer(), nullable=True),
    sa.Column('start_leasing', sa.DateTime(), nullable=True),
    sa.Column('end_leasing', sa.DateTime(), nullable=True),
    sa.Column('leasing_type', sa.Integer(), nullable=True),
    sa.Column('km_aar', sa.Float(), nullable=True),
    sa.Column('sleep', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=128), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('forvaltning', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('test_vehicle', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fuel'], ['fuel_types.id'], name=op.f('fk_cars_fuel_fuel_types')),
    sa.ForeignKeyConstraint(['leasing_type'], ['leasing_types.id'], name=op.f('fk_cars_leasing_type_leasing_types')),
    sa.ForeignKeyConstraint(['location'], ['allowed_starts.id'], name=op.f('fk_cars_location_allowed_starts')),
    sa.ForeignKeyConstraint(['type'], ['vehicle_types.id'], name=op.f('fk_cars_type_vehicle_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cars'))
    )
    op.create_table('roundtrips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('start_latitude', sa.Float(), nullable=True),
    sa.Column('start_longitude', sa.Float(), nullable=True),
    sa.Column('end_latitude', sa.Float(), nullable=True),
    sa.Column('end_longitude', sa.Float(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('aggregation_type', sa.String(length=128), nullable=True),
    sa.Column('driver_name', sa.String(length=128), nullable=True),
    sa.Column('start_location_id', sa.Integer(), nullable=True),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], name=op.f('fk_roundtrips_car_id_cars')),
    sa.ForeignKeyConstraint(['start_location_id'], ['allowed_starts.id'], name=op.f('fk_roundtrips_start_location_id_allowed_starts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roundtrips'))
    )
    with op.batch_alter_table('roundtrips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roundtrips_car_id'), ['car_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roundtrips_end_time'), ['end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_roundtrips_start_time'), ['start_time'], unique=False)

    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('start_latitude', sa.Float(), nullable=True),
    sa.Column('start_longitude', sa.Float(), nullable=True),
    sa.Column('end_latitude', sa.Float(), nullable=True),
    sa.Column('end_longitude', sa.Float(), nullable=True),
    sa.Column('driver_name', sa.String(length=128), nullable=True),
    sa.Column('department', sa.String(length=128), nullable=True),
    sa.Column('start_location', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], name=op.f('fk_trips_car_id_cars')),
    sa.ForeignKeyConstraint(['start_location'], ['allowed_starts.id'], name=op.f('fk_trips_start_location_allowed_starts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trips'))
    )
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trips_car_id'), ['car_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trips_end_time'), ['end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_trips_start_time'), ['start_time'], unique=False)

    op.create_table('workshop_visits',
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], name=op.f('fk_workshop_visits_car_id_cars')),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], name=op.f('fk_workshop_visits_workshop_id_workshops')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workshop_visits'))
    )
    with op.batch_alter_table('workshop_visits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workshop_visits_car_id'), ['car_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workshop_visits_end_time'), ['end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_workshop_visits_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_workshop_visits_workshop_id'), ['workshop_id'], unique=False)

    op.create_table('roundtripsegments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('round_trip_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['round_trip_id'], ['roundtrips.id'], name=op.f('fk_roundtripsegments_round_trip_id_roundtrips')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roundtripsegments'))
    )
    with op.batch_alter_table('roundtripsegments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roundtripsegments_round_trip_id'), ['round_trip_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roundtripsegments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roundtripsegments_round_trip_id'))

    op.drop_table('roundtripsegments')
    with op.batch_alter_table('workshop_visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workshop_visits_workshop_id'))
        batch_op.drop_index(batch_op.f('ix_workshop_visits_start_time'))
        batch_op.drop_index(batch_op.f('ix_workshop_visits_end_time'))
        batch_op.drop_index(batch_op.f('ix_workshop_visits_car_id'))

    op.drop_table('workshop_visits')
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trips_start_time'))
        batch_op.drop_index(batch_op.f('ix_trips_end_time'))
        batch_op.drop_index(batch_op.f('ix_trips_car_id'))

    op.drop_table('trips')
    with op.batch_alter_table('roundtrips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roundtrips_start_time'))
        batch_op.drop_index(batch_op.f('ix_roundtrips_end_time'))
        batch_op.drop_index(batch_op.f('ix_roundtrips_car_id'))

    op.drop_table('roundtrips')
    op.drop_table('cars')
    with op.batch_alter_table('allowed_start_additions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allowed_start_additions_allowed_start_id'))

    op.drop_table('allowed_start_additions')
    op.drop_table('workshops')
    op.drop_table('vehicle_types')
    op.drop_table('user_login')
    op.drop_table('simulation_settings')
    op.drop_table('leasing_types')
    op.drop_table('fuel_types')
    op.drop_table('allowed_starts')
    # ### end Alembic commands ###
