"""add report tables

Revision ID: e5df1ec20aa6
Revises: 99445ea7335e
Create Date: 2026-08-07 16:09:31.157283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5df1ec20aa6'
down_revision: Union[str, Sequence[str], None] = '99445ea7335e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_subscriptions',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('trigger_type', sa.String(length=64), nullable=False),
    sa.Column('schedule', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('threshold_days', sa.Integer(), nullable=True),
    sa.Column('all_vehicles', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_subscriptions'))
    )
    op.create_table('report_recipients',
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['report_subscriptions.id'], name=op.f('fk_report_recipients_subscription_id_report_subscriptions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_recipients')),
    sa.UniqueConstraint('subscription_id', 'email', name=op.f('uq_report_recipients_subscription_id'))
    )
    with op.batch_alter_table('report_recipients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_recipients_subscription_id'), ['subscription_id'], unique=False)

    op.create_table('report_alerts',
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by_user', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], name=op.f('fk_report_alerts_car_id_cars')),
    sa.ForeignKeyConstraint(['location_id'], ['allowed_starts.id'], name=op.f('fk_report_alerts_location_id_allowed_starts')),
    sa.ForeignKeyConstraint(['subscription_id'], ['report_subscriptions.id'], name=op.f('fk_report_alerts_subscription_id_report_subscriptions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_alerts'))
    )
    with op.batch_alter_table('report_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_alerts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_alerts_subscription_id'), ['subscription_id'], unique=False)

    op.create_table('report_subscription_scope',
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('forvaltning', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], name=op.f('fk_report_subscription_scope_car_id_cars')),
    sa.ForeignKeyConstraint(['location_id'], ['allowed_starts.id'], name=op.f('fk_report_subscription_scope_location_id_allowed_starts')),
    sa.ForeignKeyConstraint(['subscription_id'], ['report_subscriptions.id'], name=op.f('fk_report_subscription_scope_subscription_id_report_subscriptions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_subscription_scope'))
    )
    with op.batch_alter_table('report_subscription_scope', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_subscription_scope_subscription_id'), ['subscription_id'], unique=False)

    op.create_table('report_deliveries',
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('recipient_email', sa.String(length=256), nullable=False),
    sa.Column('subject', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['report_alerts.id'], name=op.f('fk_report_deliveries_alert_id_report_alerts')),
    sa.ForeignKeyConstraint(['subscription_id'], ['report_subscriptions.id'], name=op.f('fk_report_deliveries_subscription_id_report_subscriptions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_deliveries'))
    )
    with op.batch_alter_table('report_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_deliveries_subscription_id'), ['subscription_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_deliveries_subscription_id'))

    op.drop_table('report_deliveries')
    with op.batch_alter_table('report_subscription_scope', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_subscription_scope_subscription_id'))

    op.drop_table('report_subscription_scope')
    with op.batch_alter_table('report_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_alerts_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_report_alerts_status'))

    op.drop_table('report_alerts')
    with op.batch_alter_table('report_recipients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_recipients_subscription_id'))

    op.drop_table('report_recipients')
    op.drop_table('report_subscriptions')
    # ### end Alembic commands ###
