name: Frontend build, test and push

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*.*.*'
    paths:
      - 'fleetoptimiser-frontend/**'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: fleetoptimiser-frontend

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: actions/checkout@v4

      - name: Log into registry ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          push: false
          context: fleetoptimiser-frontend
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest