name: Frontend build, test and push

on:
  push:
    tags:
      - 'v*.*.*'
    paths:
      - 'fleetoptimiser-frontend/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: fleetoptimiser-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: actions/checkout@v4

      - name: Lowercase repository name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Log into registry ghcr.io
        uses: docker/login-action@v3.3
        with:
          registry: ${{ env.REGISTRY }}/${{ OWNER_LC }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: fleetoptimiser-frontend
          tags: |
            ${{ env.REGISTRY }}/${{ OWNER_LC }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            ${{ env.REGISTRY }}/${{ OWNER_LC }}/${{ env.IMAGE_NAME }}:latest