name: Deploy to testing

on:
  push:
    branches:
      - 'testing'
env:
  REGISTRY: ghcr.io
  BACKEND_IMAGE_NAME: fleetoptimiser-backend
  FRONTEND_IMAGE_NAME: fleetoptimiser-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: actions/checkout@v4

      - name: Lowercase repository name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Log into registry ghcr.io
        uses: docker/login-action@v3.3
        with:
          registry: ${{ env.REGISTRY }}/${{ OWNER_LC }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ OWNER_LC }}/${{ env.BACKEND_IMAGE_NAME }}:testing

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: fleetoptimiser-frontend
          tags: |
            ${{ env.REGISTRY }}/${{ OWNER_LC }}/${{ env.FRONTEND_IMAGE_NAME }}:testing

      - name: Trigger webhook
        run: |
          curl -X POST https://listener.fleetoptimiser.droidsagencyai.com/webhook \
          -H "Content-Type: application/json" \
          -H "x-hub-signature: $WEBHOOK_SECRET" \
          -d "{\"tag\": \"testing\"}"
        env:
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
